name: Push Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Nom du tag à pousser'
        required: true

jobs:
  push-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Créer et pousser le tag
        run: |
          git tag ${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }}
